---
title: "TFid_translation"
author: "Edward Zhu"
date: "`r Sys.Date()`"
output: html_document
---

Translate `ZMGRM_` formatted gene ids to `Zm000d_` style B73v4 compatible gene ids for further analysis

```{r}
TF_table = read.table("./Zma_TF_list.txt", sep = "\t")
colnames(TF_table) = TF_table[1,]
TF_table = TF_table[-1,]
```

```{r}
# Output for conversion
# TF_gene_id = TF_table[,2]
# write.csv(TF_gene_id, file = "ZM_TF_geneid.csv")
TF_geneid_translation = read.table("./Zma_geneid_translated.txt", sep = "\t", na.strings = NA, fill = T, col.names = c("gene_id_bf", "gene_id_af", 1:6))[-1,1:2]
```

为转换完成的Gene加上TF Family信息

```{r}
TF_geneid_translation$family = NA

for (i in 1:nrow(TF_geneid_translation)) {
  TF_geneid_translation[i,3] = TF_table[which(TF_table$Gene_ID == TF_geneid_translation[i,1]),3][1]
}

TF_geneid_translation$family = as.factor(TF_geneid_translation$family)
```

Visualize一下family分布情况

```{r}
library(tidyverse)
library(plotly)
library(ggthemes)

plt1 = ggplot(data=TF_geneid_translation, aes(x=family)) +
  geom_bar(fill="#66CCCC") +
  theme_calc() +
  theme(axis.text.x = element_text(angle = 90, size = 6),
        legend.position = 'none',
        axis.ticks.x = element_blank(),
        ) +
  labs(x = 'TF family')

htmlwidgets::saveWidget(ggplotly(plt1), "Zea_mays_TF_overview.html")
```
